spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/cloud-storage
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
