spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/cloud-storage
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
minio:
  endpoint: http://localhost:9000
  user: admin
  password: password
  bucket: user-files
logging:
  level:
    org.springframework.security: DEBUG